### ISSUE TITLE
(8) - Sync with Database

### ISSUE THREAD

**Issue by babbett** [gordon-cs/ampm-catalyst#8]
As an AM/PM staff member, I want to be certain that I am accessing the most recent version of the database available. While the actual syncing should be done automatically, I should be able to quickly see the last time that the system was synced. This user story requires that there is an actual offline/online database system set up.

Tasks:
- [x] Setup new AWS instance
- [x] Add SymmetricDS to instance
- [ ] Create database on AWS
- [x] Create Param file on AWS
- [x] Create local DB
- [x] Java wrapper class for local

**Comment by russtuck** [comment]
With Ben leaving the project, we're dropping offline mode.  Closing this because there's nobody to do it.
